import type { SettingsResponse } from "../types";

export const mockSettings: SettingsResponse = {
  general: {
    companyName: "Abroad Scholars CRM",
    logoUrl: "",
    timezone: "Asia/Kolkata",
    currency: "INR",
    dateFormat: "DD/MM/YYYY",
    language: "en",
  },
  pipelineStages: [
    { id: "s1", name: "New", color: "#3b82f6", order: 1, isDefault: true },
    {
      id: "s2",
      name: "In Progress",
      color: "#f59e0b",
      order: 2,
      isDefault: true,
    },
    {
      id: "s3",
      name: "Converted",
      color: "#10b981",
      order: 3,
      isDefault: true,
    },
    { id: "s4", name: "Lost", color: "#94a3b8", order: 4, isDefault: true },
  ],
  categories: [
    { id: "c1", name: "Admission", color: "#8b5cf6" },
    { id: "c2", name: "IELTS", color: "#3b82f6" },
    { id: "c3", name: "Visa", color: "#f59e0b" },
    { id: "c4", name: "Coaching", color: "#10b981" },
  ],
  qualities: [
    { id: "q1", name: "Hot", color: "#e11d48" },
    { id: "q2", name: "Warm", color: "#f59e0b" },
    { id: "q3", name: "Cold", color: "#0ea5e9" },
  ],
  countries: [
    { id: "co1", name: "United Kingdom", code: "UK", isActive: true },
    { id: "co2", name: "Canada", code: "CA", isActive: true },
    { id: "co3", name: "Australia", code: "AU", isActive: true },
    { id: "co4", name: "United States", code: "US", isActive: true },
    { id: "co5", name: "Germany", code: "DE", isActive: true },
    { id: "co6", name: "New Zealand", code: "NZ", isActive: false },
    { id: "co7", name: "Ireland", code: "IE", isActive: false },
  ],
  assignmentRules: [
    {
      id: "a1",
      name: "Default Round Robin",
      type: "round_robin",
      isActive: true,
      counselors: ["Oviya", "Jai", "Priya"],
    },
    {
      id: "a2",
      name: "UK Leads → Oviya",
      type: "rule_based",
      isActive: true,
      counselors: ["Oviya"],
      conditions: [{ field: "country", operator: "eq", value: "UK" }],
    },
    {
      id: "a3",
      name: "IELTS Leads → Priya",
      type: "rule_based",
      isActive: false,
      counselors: ["Priya"],
      conditions: [{ field: "category", operator: "eq", value: "IELTS" }],
    },
  ],
  notifications: [
    {
      id: "n1",
      event: "New Lead Assigned",
      description: "When a new lead is assigned to you",
      inApp: true,
      email: true,
      category: "leads",
    },
    {
      id: "n2",
      event: "Lead Converted",
      description: "When a lead status changes to Converted",
      inApp: true,
      email: false,
      category: "leads",
    },
    {
      id: "n3",
      event: "Follow-up Due",
      description: "Reminder when a follow-up date arrives",
      inApp: true,
      email: true,
      category: "leads",
    },
    {
      id: "n4",
      event: "Lead Lost",
      description: "When a lead is marked as Lost",
      inApp: true,
      email: false,
      category: "leads",
    },
    {
      id: "n5",
      event: "New User Added",
      description: "When a new team member joins",
      inApp: true,
      email: false,
      category: "team",
    },
    {
      id: "n6",
      event: "Counselor Performance Alert",
      description: "Weekly performance digest",
      inApp: false,
      email: true,
      category: "team",
    },
    {
      id: "n7",
      event: "Budget Alert Triggered",
      description: "When a marketing budget alert fires",
      inApp: true,
      email: true,
      category: "marketing",
    },
    {
      id: "n8",
      event: "Sync Failed",
      description: "When a webhook sync fails",
      inApp: true,
      email: true,
      category: "marketing",
    },
    {
      id: "n9",
      event: "Daily Summary",
      description: "Daily lead and performance summary",
      inApp: false,
      email: true,
      category: "system",
    },
    {
      id: "n10",
      event: "System Maintenance",
      description: "Scheduled maintenance notifications",
      inApp: true,
      email: true,
      category: "system",
    },
  ],
  webhooks: [
    {
      id: "w1",
      platform: "meta",
      webhookUrl: "https://crm.abroadscholars.in/api/webhooks/meta",
      secret: "whsec_meta_****",
      isActive: true,
      lastPing: "2026-05-20T12:30:00",
    },
    {
      id: "w2",
      platform: "google",
      webhookUrl: "https://crm.abroadscholars.in/api/webhooks/google",
      secret: "whsec_google_****",
      isActive: false,
      lastPing: null,
    },
  ],
  emailTemplates: [
    {
      id: "e1",
      name: "Lead Assignment",
      subject: "New Lead Assigned: {{lead_name}}",
      description: "Sent to counselor when a new lead is assigned",
      isActive: true,
      lastEdited: "2026-05-15T10:00:00",
    },
    {
      id: "e2",
      name: "Follow-up Reminder",
      subject: "Follow-up Due: {{lead_name}}",
      description: "Sent when a follow-up date is approaching",
      isActive: true,
      lastEdited: "2026-05-12T14:00:00",
    },
    {
      id: "e3",
      name: "Welcome Email",
      subject: "Welcome to Abroad Scholars!",
      description: "Sent to new leads from website",
      isActive: false,
      lastEdited: "2026-05-01T09:00:00",
    },
    {
      id: "e4",
      name: "Weekly Report",
      subject: "Your Weekly Performance Report",
      description: "Weekly counselor performance digest",
      isActive: true,
      lastEdited: "2026-05-10T11:00:00",
    },
  ],
  smtp: {
    host: "smtp.gmail.com",
    port: 587,
    username: "crm@abroadscholars.in",
    encryption: "tls",
    fromEmail: "crm@abroadscholars.in",
    fromName: "Abroad Scholars CRM",
  },
  auditLogs: [
    {
      id: "au1",
      user: "Jai",
      action: "Updated",
      target: "Pipeline Stage",
      details: "Added 'Follow Up' stage",
      timestamp: "2026-05-20T11:30:00",
      category: "settings",
    },
    {
      id: "au2",
      user: "Oviya",
      action: "Converted",
      target: "Lead: Bala Ravi",
      details: "Status changed to Converted",
      timestamp: "2026-05-20T10:15:00",
      category: "lead",
    },
    {
      id: "au3",
      user: "Jai",
      action: "Created",
      target: "User: Priya",
      details: "Added new counselor",
      timestamp: "2026-05-19T16:00:00",
      category: "user",
    },
    {
      id: "au4",
      user: "System",
      action: "Triggered",
      target: "Alert: High CPL",
      details: "CPL exceeded ₹500 threshold",
      timestamp: "2026-05-19T14:20:00",
      category: "marketing",
    },
    {
      id: "au5",
      user: "Jai",
      action: "Updated",
      target: "Assignment Rule",
      details: "Changed UK leads assignment to Oviya",
      timestamp: "2026-05-18T09:45:00",
      category: "settings",
    },
    {
      id: "au6",
      user: "Priya",
      action: "Lost",
      target: "Lead: Vikram Singh",
      details: "Marked as lost - no response",
      timestamp: "2026-05-18T08:30:00",
      category: "lead",
    },
    {
      id: "au7",
      user: "System",
      action: "Synced",
      target: "Meta Webhook",
      details: "15 leads synced successfully",
      timestamp: "2026-05-17T23:00:00",
      category: "marketing",
    },
    {
      id: "au8",
      user: "Jai",
      action: "Exported",
      target: "All Leads",
      details: "Exported 642 leads to CSV",
      timestamp: "2026-05-17T15:30:00",
      category: "lead",
    },
  ],
};
