import type { IeltsRecord } from "../Types";

export const DUMMY_IELTS_RECORDS: IeltsRecord[] = [
  {
    id: "1",
    studentId: "s1",
    studentName: "Abhishek Yadav",
    country: "Germany",
    counselor: "Arjun Patel",
    status: "Preparing",
    examDate: "2026-06-15",
    examType: "Academic",
    targetScore: {
      listening: 7.0,
      reading: 7.0,
      writing: 6.5,
      speaking: 6.5,
      overall: 7.0,
    },
    currentScore: {
      listening: 6.5,
      reading: 6.0,
      writing: 5.5,
      speaking: 6.0,
      overall: 6.0,
    },
    attempts: 1,
    lastUpdated: "2026-05-18",
    notes: "Needs improvement in writing. Enrolled in crash course.",
    registrationId: "IDP-2026-4821",
    preparationStartDate: "2026-03-01",
    university: "TU Munich",
    requiredScore: 7.0,
  },
  {
    id: "2",
    studentId: "s2",
    studentName: "Rajesh Pillai",
    country: "Australia",
    counselor: "Rohan Mehta",
    status: "Scheduled",
    examDate: "2026-06-02",
    examType: "Academic",
    targetScore: {
      listening: 7.5,
      reading: 7.0,
      writing: 6.5,
      speaking: 7.0,
      overall: 7.0,
    },
    currentScore: {
      listening: 7.0,
      reading: 6.5,
      writing: 6.0,
      speaking: 6.5,
      overall: 6.5,
    },
    attempts: 2,
    lastUpdated: "2026-05-15",
    notes: "Second attempt. Improved listening significantly.",
    registrationId: "BC-2026-7712",
    preparationStartDate: "2026-01-10",
    university: "University of Melbourne",
    requiredScore: 7.0,
  },
  {
    id: "3",
    studentId: "s3",
    studentName: "Priya Sharma",
    country: "Canada",
    counselor: "Arjun Patel",
    status: "Completed",
    examDate: "2026-04-20",
    examType: "Academic",
    targetScore: {
      listening: 7.0,
      reading: 7.0,
      writing: 6.5,
      speaking: 6.5,
      overall: 7.0,
    },
    currentScore: {
      listening: 8.0,
      reading: 7.5,
      writing: 7.0,
      speaking: 7.0,
      overall: 7.5,
    },
    attempts: 1,
    lastUpdated: "2026-05-01",
    notes: "Exceeded target in all modules! Ready for application.",
    registrationId: "IDP-2026-3390",
    preparationStartDate: "2026-01-15",
    university: "University of Toronto",
    requiredScore: 7.0,
  },
  {
    id: "4",
    studentId: "s4",
    studentName: "Kiran Nair",
    country: "UK",
    counselor: "Rohan Mehta",
    status: "Preparing",
    examDate: "2026-07-10",
    examType: "Academic",
    targetScore: {
      listening: 7.5,
      reading: 7.5,
      writing: 7.0,
      speaking: 7.0,
      overall: 7.5,
    },
    currentScore: {
      listening: 6.0,
      reading: 6.5,
      writing: 5.5,
      speaking: 6.0,
      overall: 6.0,
    },
    attempts: 0,
    lastUpdated: "2026-05-20",
    notes: "Mock test scores. Weak in writing. Extra coaching scheduled.",
    registrationId: "",
    preparationStartDate: "2026-04-01",
    university: "Imperial College London",
    requiredScore: 7.5,
  },
  {
    id: "5",
    studentId: "s5",
    studentName: "Sneha Reddy",
    country: "Australia",
    counselor: "Ganesh Kumar",
    status: "Completed",
    examDate: "2026-03-25",
    examType: "General Training",
    targetScore: {
      listening: 7.0,
      reading: 6.5,
      writing: 6.5,
      speaking: 7.0,
      overall: 7.0,
    },
    currentScore: {
      listening: 7.5,
      reading: 7.0,
      writing: 6.5,
      speaking: 7.5,
      overall: 7.0,
    },
    attempts: 1,
    lastUpdated: "2026-04-10",
    notes: "Target met. Visa application in progress.",
    registrationId: "IDP-2026-5501",
    preparationStartDate: "2025-12-01",
    university: "Monash University",
    requiredScore: 7.0,
  },
  {
    id: "6",
    studentId: "s6",
    studentName: "Arun Menon",
    country: "Canada",
    counselor: "Ganesh Kumar",
    status: "Not Started",
    examDate: null,
    examType: "Academic",
    targetScore: {
      listening: 6.5,
      reading: 6.5,
      writing: 6.0,
      speaking: 6.0,
      overall: 6.5,
    },
    currentScore: null,
    attempts: 0,
    lastUpdated: "2026-05-19",
    notes: "Joining coaching next week.",
    registrationId: "",
    preparationStartDate: null,
    university: "University of British Columbia",
    requiredScore: 6.5,
  },
  {
    id: "7",
    studentId: "s7",
    studentName: "Meera Joshi",
    country: "Ireland",
    counselor: "Arjun Patel",
    status: "Scheduled",
    examDate: "2026-05-28",
    examType: "Academic",
    targetScore: {
      listening: 6.5,
      reading: 6.5,
      writing: 6.0,
      speaking: 6.5,
      overall: 6.5,
    },
    currentScore: {
      listening: 6.5,
      reading: 6.0,
      writing: 5.5,
      speaking: 6.0,
      overall: 6.0,
    },
    attempts: 1,
    lastUpdated: "2026-05-10",
    notes: "Exam in 7 days. Final mock scored 6.0 overall.",
    registrationId: "BC-2026-8823",
    preparationStartDate: "2026-02-15",
    university: "Trinity College Dublin",
    requiredScore: 6.5,
  },
  {
    id: "8",
    studentId: "s8",
    studentName: "Vikram Singh",
    country: "USA",
    counselor: "Rohan Mehta",
    status: "Completed",
    examDate: "2026-04-05",
    examType: "Academic",
    targetScore: {
      listening: 7.0,
      reading: 7.0,
      writing: 6.5,
      speaking: 7.0,
      overall: 7.0,
    },
    currentScore: {
      listening: 6.5,
      reading: 7.0,
      writing: 6.0,
      speaking: 6.5,
      overall: 6.5,
    },
    attempts: 2,
    lastUpdated: "2026-04-20",
    notes: "Missed target by 0.5. Considering retake.",
    registrationId: "IDP-2026-2209",
    preparationStartDate: "2025-11-01",
    university: "Arizona State University",
    requiredScore: 7.0,
  },
  {
    id: "9",
    studentId: "s9",
    studentName: "Ananya Das",
    country: "New Zealand",
    counselor: "Ganesh Kumar",
    status: "Preparing",
    examDate: "2026-08-01",
    examType: "General Training",
    targetScore: {
      listening: 6.5,
      reading: 6.0,
      writing: 6.0,
      speaking: 6.5,
      overall: 6.5,
    },
    currentScore: {
      listening: 5.5,
      reading: 5.0,
      writing: 5.0,
      speaking: 5.5,
      overall: 5.5,
    },
    attempts: 0,
    lastUpdated: "2026-05-21",
    notes: "Early preparation stage. Enrolled in full course.",
    registrationId: "",
    preparationStartDate: "2026-05-01",
    university: "University of Auckland",
    requiredScore: 6.5,
  },
  {
    id: "10",
    studentId: "s10",
    studentName: "Rahul Verma",
    country: "UK",
    counselor: "Arjun Patel",
    status: "Cancelled",
    examDate: "2026-05-10",
    examType: "Academic",
    targetScore: {
      listening: 7.0,
      reading: 7.0,
      writing: 6.5,
      speaking: 6.5,
      overall: 7.0,
    },
    currentScore: null,
    attempts: 0,
    lastUpdated: "2026-05-08",
    notes: "Student deferred admission. Will rebook later.",
    registrationId: "IDP-2026-6641",
    preparationStartDate: "2026-02-01",
    university: "University of Manchester",
    requiredScore: 7.0,
  },
  {
    id: "11",
    studentId: "s11",
    studentName: "Divya Krishnan",
    country: "Australia",
    counselor: "Rohan Mehta",
    status: "Preparing",
    examDate: "2026-06-20",
    examType: "Academic",
    targetScore: {
      listening: 8.0,
      reading: 7.5,
      writing: 7.0,
      speaking: 7.5,
      overall: 7.5,
    },
    currentScore: {
      listening: 7.0,
      reading: 7.0,
      writing: 6.0,
      speaking: 6.5,
      overall: 6.5,
    },
    attempts: 1,
    lastUpdated: "2026-05-17",
    notes: "Targeting nursing registration. Needs 7.0 in each module.",
    registrationId: "BC-2026-1155",
    preparationStartDate: "2026-03-15",
    university: "University of Sydney",
    requiredScore: 7.5,
  },
  {
    id: "12",
    studentId: "s12",
    studentName: "Sanjay Gupta",
    country: "Canada",
    counselor: "Ganesh Kumar",
    status: "Not Started",
    examDate: null,
    examType: "Academic",
    targetScore: {
      listening: 6.5,
      reading: 6.5,
      writing: 6.0,
      speaking: 6.0,
      overall: 6.5,
    },
    currentScore: null,
    attempts: 0,
    lastUpdated: "2026-05-20",
    notes: "Enquiry stage. Counselor to follow up.",
    registrationId: "",
    preparationStartDate: null,
    university: "McGill University",
    requiredScore: 6.5,
  },
];
