import type { AlertLog, AlertRule, AlertStats, RuleTemplate } from "../types/Index";


export const formatDateTime = (dateStr: string): string =>
  new Date(dateStr).toLocaleDateString("en-IN", {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

export const timeAgo = (dateStr: string): string => {
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
};

// ─── Mock stats ───
export const mockStats: AlertStats = {
  totalRules: 6,
  activeRules: 4,
  triggeredToday: 3,
  criticalAlerts: 1,
  warningAlerts: 2,
  infoAlerts: 4,
};

// ─── Mock rules ───
export const mockRules: AlertRule[] = [
  {
    id: "r1",
    name: "High CPL Alert",
    description: "Notify when cost per lead exceeds ₹500",
    type: "budget",
    condition: { metric: "cpl", operator: "gt", value: 500, unit: "₹" },
    action: { type: "notification" },
    isActive: true,
    createdAt: "2026-05-01T10:00:00",
    lastTriggered: "2026-05-18T09:15:00",
    triggerCount: 3,
  },
  {
    id: "r2",
    name: "Daily Spend Cap",
    description: "Alert when daily spend exceeds ₹5,000",
    type: "budget",
    condition: { metric: "dailySpend", operator: "gt", value: 5000, unit: "₹" },
    action: { type: "email", target: "jai@abroadscholars.in" },
    isActive: true,
    createdAt: "2026-05-02T11:00:00",
    lastTriggered: "2026-05-17T16:30:00",
    triggerCount: 5,
  },
  {
    id: "r3",
    name: "No Sync Warning",
    description: "Alert if no leads sync for 48 hours",
    type: "sync",
    condition: { metric: "syncGap", operator: "gt", value: 48, unit: "hours" },
    action: { type: "notification" },
    isActive: true,
    createdAt: "2026-05-05T09:00:00",
    lastTriggered: null,
    triggerCount: 0,
  },
  {
    id: "r4",
    name: "Low Conversion Rate",
    description: "Alert when conversion rate drops below 2%",
    type: "performance",
    condition: {
      metric: "conversionRate",
      operator: "lt",
      value: 2,
      unit: "%",
    },
    action: { type: "notification" },
    isActive: true,
    createdAt: "2026-05-06T14:00:00",
    lastTriggered: "2026-05-18T11:00:00",
    triggerCount: 2,
  },
  {
    id: "r5",
    name: "High Cold Lead %",
    description: "Warn when cold leads exceed 50% of total",
    type: "quality",
    condition: {
      metric: "coldLeadPercent",
      operator: "gt",
      value: 50,
      unit: "%",
    },
    action: { type: "email", target: "jai@abroadscholars.in" },
    isActive: false,
    createdAt: "2026-05-08T10:00:00",
    lastTriggered: null,
    triggerCount: 0,
  },
  {
    id: "r6",
    name: "Slow Response Time",
    description: "Alert when avg response time exceeds 60 minutes",
    type: "response",
    condition: {
      metric: "responseTime",
      operator: "gt",
      value: 60,
      unit: "mins",
    },
    action: { type: "assign_counselor" },
    isActive: false,
    createdAt: "2026-05-10T08:00:00",
    lastTriggered: null,
    triggerCount: 0,
  },
];

// ─── Mock alert logs ───
export const mockLogs: AlertLog[] = [
  {
    id: "l1",
    ruleId: "r4",
    ruleName: "Low Conversion Rate",
    type: "performance",
    message: "Vp_ads conversion rate dropped to 1.6%, below 2% threshold",
    severity: "critical",
    triggeredAt: "2026-05-18T11:00:00",
    isRead: false,
    campaignName: "Vp_ads",
    currentValue: "1.6%",
    thresholdValue: "2%",
  },
  {
    id: "l2",
    ruleId: "r2",
    ruleName: "Daily Spend Cap",
    type: "budget",
    message: "Daily spend reached ₹5,420, exceeding ₹5,000 cap",
    severity: "warning",
    triggeredAt: "2026-05-17T16:30:00",
    isRead: false,
    campaignName: "IELTS Coaching 9999/-",
    currentValue: "₹5,420",
    thresholdValue: "₹5,000",
  },
  {
    id: "l3",
    ruleId: "r1",
    ruleName: "High CPL Alert",
    type: "budget",
    message: "UK Universities CPL reached ₹527, above ₹500 threshold",
    severity: "warning",
    triggeredAt: "2026-05-18T09:15:00",
    isRead: true,
    campaignName: "UK Universities - May",
    currentValue: "₹527",
    thresholdValue: "₹500",
  },
  {
    id: "l4",
    ruleId: "r4",
    ruleName: "Low Conversion Rate",
    type: "performance",
    message: "Canada PR Pathway conversion rate at 2.6%, near threshold",
    severity: "info",
    triggeredAt: "2026-05-16T14:20:00",
    isRead: true,
    campaignName: "Canada PR Pathway",
    currentValue: "2.6%",
    thresholdValue: "2%",
  },
  {
    id: "l5",
    ruleId: "r2",
    ruleName: "Daily Spend Cap",
    type: "budget",
    message: "Daily spend reached ₹5,180 across all campaigns",
    severity: "warning",
    triggeredAt: "2026-05-15T17:00:00",
    isRead: true,
    currentValue: "₹5,180",
    thresholdValue: "₹5,000",
  },
  {
    id: "l6",
    ruleId: "r1",
    ruleName: "High CPL Alert",
    type: "budget",
    message: "Vp_ads CPL spiked to ₹612 in the last 24 hours",
    severity: "critical",
    triggeredAt: "2026-05-14T10:45:00",
    isRead: true,
    campaignName: "Vp_ads",
    currentValue: "₹612",
    thresholdValue: "₹500",
  },
  {
    id: "l7",
    ruleId: "r4",
    ruleName: "Low Conversion Rate",
    type: "performance",
    message: "Overall conversion rate dropped to 3.8%",
    severity: "info",
    triggeredAt: "2026-05-13T09:00:00",
    isRead: true,
    currentValue: "3.8%",
    thresholdValue: "2%",
  },
];

// ─── Rule templates for quick creation ───
export const mockTemplates: RuleTemplate[] = [
  {
    id: "t1",
    name: "Budget Cap",
    description: "Alert when daily spend exceeds a limit",
    type: "budget",
    icon: "money",
    defaultCondition: {
      metric: "dailySpend",
      operator: "gt",
      value: 5000,
      unit: "₹",
    },
    defaultAction: { type: "notification" },
  },
  {
    id: "t2",
    name: "CPL Threshold",
    description: "Warn when cost per lead gets too high",
    type: "budget",
    icon: "tag",
    defaultCondition: { metric: "cpl", operator: "gt", value: 300, unit: "₹" },
    defaultAction: { type: "notification" },
  },
  {
    id: "t3",
    name: "Low Conversion",
    description: "Alert on dropping conversion rates",
    type: "performance",
    icon: "chart",
    defaultCondition: {
      metric: "conversionRate",
      operator: "lt",
      value: 3,
      unit: "%",
    },
    defaultAction: { type: "email" },
  },
  {
    id: "t4",
    name: "Sync Monitor",
    description: "Detect when lead sync stops",
    type: "sync",
    icon: "sync",
    defaultCondition: {
      metric: "syncGap",
      operator: "gt",
      value: 24,
      unit: "hours",
    },
    defaultAction: { type: "notification" },
  },
  {
    id: "t5",
    name: "Lead Quality Drop",
    description: "Warn when cold leads dominate",
    type: "quality",
    icon: "quality",
    defaultCondition: {
      metric: "coldLeadPercent",
      operator: "gt",
      value: 40,
      unit: "%",
    },
    defaultAction: { type: "notification" },
  },
  {
    id: "t6",
    name: "Slow Response",
    description: "Alert on high counselor response time",
    type: "response",
    icon: "clock",
    defaultCondition: {
      metric: "responseTime",
      operator: "gt",
      value: 45,
      unit: "mins",
    },
    defaultAction: { type: "assign_counselor" },
  },
];
